[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/deoplete-rct'
on_ft = ['ruby']

[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'osyo-manga/vim-monster'
on_i = 1
hook_add = '''
	let g:monster#completion#rcodetools#backend = "async_rct_complete"
	let g:deoplete#sources#omni#input_patterns = {
  \ "ruby" : '[^. *\t]\.\w*\|\h\w*::',
  \}
'''

[[plugins]]
repo = 'tpope/vim-endwise'
on_i = 1
on_ft = ['ruby']

[[plugins]]
repo = 'deoplete-plugins/deoplete-jedi'
on_i = 1
on_ft = ['python3','python']

[[plugins]]
repo = 'mattn/sonictemplate-vim'
on_i = 1
on_cmd = ['Template']
hook_add = '''
	let g:sonictemplate_vim_template_dir = [
\ '$HOME/.config/nvim/template',
\]
'''
