[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']


[[plugins]]
repo = 'osyo-manga/vim-monster'
on_i = 1
hook_add = '''
	let g:monster#completion#rcodetools#backend = "async_rct_complete"
	let g:monster#completion#backend = 'solargraph'
'''
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-endwise'
on_i = 1
on_ft = ['ruby']

[[plugins]]
repo = 'mattn/sonictemplate-vim'
on_i = 1
on_cmd = ['Template']
hook_add = '''
	let g:sonictemplate_vim_template_dir = [
\ '$HOME/.config/nvim/template',
\]
'''

