[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'scrooloose/syntastic'
hook_add = '''
  let g:syntastic_enable_signs=1
  let g:syntastic_auto_loc_list=2
  let g:syntastic_enable_perl_checker = 1
  let g:syntastic_perl_checkers = ['perl','podchecker']
  "let g:syntastic_debug = 1
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
"hook_add = '''
" noremap <C-N> :NERDTree<CR>
"'''
[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
hook_add = '''
	map <C-n> <plug>NERDTreeTabsToggle<CR>
'''

[[plugins]]
repo = 'reireias/vim-cheatsheet'
hook_add = '''
	let g:cheatsheet#cheat_file = '~/.cheatsheet.txt'
'''

[[plugins]]
repo = 'c9s/perlomni.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'hotchpotch/perldoc-vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
  let g:quickrun_config = get(g:, 'quickrun_config', {})
  "bundlecheckした結果によってbundle execが必要かどうかを判定するコマンドを新たに作ったのでそれを参照させる
  "momo-labさんのQiita記事に感謝
  let g:quickrun_config = {
            \ 'ruby': { 'command': $HOME.'/bin/ruby' },
            \ 'outputter/buffer/split': '10',
						\ 'python': {'command': '/usr/local/bin/python3'}
            \ }
  nnoremap <expr><silent> <C-c> quickrun#is_running() ? quickrun#sweep_sessions() : "\<C-c>"

'''

[[plugins]]
repo = 'vim-perl/vim-perl'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'rsense/rsense'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'KKPMW/moonshine-vim'

[[plugins]]
repo = 'sjl/badwolf'

[[plugins]]
repo = 'ravelll/vim-murk'

[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
  let g:gruvbox_contrast_dark = 'hard'
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'itchyny/vim-parenmatch'
hook_add = '''
  let g:loaded_matchparen = 1
'''
[[plugins]]
repo = 'itchyny/vim-cursorword'

[[plugins]]
repo = 'lepture/vim-jinja'
hook_add = '''
	au BufNewFile,BufRead *.j2,*.tmpl,*.shtml,*.stm set ft=jinja
'''
[[plugins]]
repo = 'neoclide/coc.nvim'
build = 'coc#util#install()'
hook_add = '''
  nmap <silent> gd <Plug>(coc-definition)
  nmap <silent> gy <Plug>(coc-type-definition)
  nmap <silent> gi <Plug>(coc-implementation)
  nmap <silent> gr <Plug>(coc-references) " Remap for rename current word
  nmap <leader>rn <Plug>(coc-rename)
  " Highlight symbol under cursor on CursorHold
  autocmd CursorHold * silent call CocActionAsync('highlight')
  " Use K for show documentation in preview window
  nnoremap <silent> K :call <SID>show_documentation()<CR>
  function! s:show_documentation()
    if &filetype == 'vim'
      execute 'h '.expand('<cword>')
    else
      call CocAction('doHover')
    endif
  endfunction
'''
marge = 0
